apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  DB_HOST: ZGI=
  DEBUG: "VHJ1ZQ=="
  POSTGRES_DB: dHV0b3JpYWwtZGV2
  POSTGRES_PASSWORD: S2pkeWVscnNqQCM=
  POSTGRES_USER: cm9vdA==
  SECRET_KEY: N3MjcDd3cng3KDhqZj0xcmgrbUBzdUB2KnVuXmM4d3YwbDMmX21qJTYtbw==
