---
# tasks file for gitlab-ci
- name: Update the apt package index in Ubuntu server
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Download script for adding gitlab-runner repo (Debian)
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: /tmp/gl_script.sh
    mode: u+x

- name: Add gitlab-runner repo
  shell: /tmp/gl_script.sh

- name: Install the latest version of GitLab Runner
  ansible.builtin.apt:
    name:
      - gitlab-runner
    state: present
    update_cache: yes

