# tasks file for docker-ubuntu
- name: Update the apt package index in SRV server
  become: yes
  apt:
    update_cache: yes
    force_apt_get: yes

- name: install docker package
  become: yes
  package:
    name: docker
    state: latest

- name: install docker.io package
  become: yes
  package:
    name: docker.io
    state: latest

- name: Docker start
  become: yes
  ansible.builtin.systemd:
    name: docker
    state: restarted
